name: .NET Core

on:
  push:
    branches: 
    - '**'
  pull_request:
    branches: 
    - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

    - name: Install dungeon crawlers app dependencies
      working-directory: ./DungeonCrawlers
      run: dotnet restore
    - name: Build dungeon crawlers app
      working-directory: ./DungeonCrawlers
      run: dotnet build --configuration Release --no-restore
    - name: Install dungeon crawlers app test dependencies
      working-directory: ./DungeonCrawlersTests
      run: dotnet restore
    - name: Test dungeon crawlers app
      working-directory: ./DungeonCrawlersTests
      run: dotnet test --no-restore --verbosity normal
